spring:
  cloud:
    gateway:
      routes:
        - id: user-products
          uri: http://localhost:9006/user/products
          predicates:
            - Header=X-API,user-products
        - id: cbu
          uri: https://cbu.uz/uz/arkhiv-kursov-valyut/json/
          predicates:
            - Method=GET
